<?php
/**
 * Adding query backend for compound children fetch
 *
 * @return array
 */
function flat_access_level_display_islandora_compound_object_query_backends() {

    $module_path = drupal_get_path('module', 'flat_access_level_display');

    return [
        'flat_access_level_display_query_backend' => [
            'title' => t('SOLR Flat - Does a Solr query with filters and adds access level. Configure fields on the <a href="@solr">Solr Backend</a> tab.',
                ['@solr' => url('admin/islandora/solution_pack_config/compound_object/solr')]
            ),
            'callable' => 'flat_access_level_display_compound_object_query',
            'file' => $module_path . '/includes/backend.inc',
        ],
    ];
}

/**
 * Registering themes
 *
 * @param array $existing
 * @param string $type
 * @param string $theme
 * @param string $path
 *
 * @return array
 */
function flat_access_level_display_theme($existing, $type, $theme, $path) {

    return [

        // this theme gets called from within islandora_compound_object module
        // and we then override it using template defined above
        'flat_access_level_display_display_label' => [

            'function'  => 'flat_access_level_display_display_label',
            'variables' => [
                'roles' => null,
            ],
        ],

        'flat_access_level_display_display_label_template' => [
            'template' => 'theme/flat-access-level-display-display-label',
        ],

        'flat_access_level_display_facets' => [
            'template' => 'theme/flat-access-level-display-facets',
        ],
    ];
}

/**
 * Theme that is called when displaying access level
 *
 * @param array $vars
 *
 * @return void
 */
function flat_access_level_display_display_label(&$vars) {

    drupal_add_css(drupal_get_path('module', 'flat_access_level_display') . '/css/app.css');
    module_load_include('inc', 'flat_access_level_display', 'includes/AccessLevel');

    $vars['roles'] = $vars['roles'] ?? [];

    $accessLevel = new AccessLevel();

    return theme('flat_access_level_display_display_label_template', [
        'access_level' => $accessLevel->fetch($vars['roles']),
    ]);
}

/**
 * Islandora solr Facet wrapper preprocessor
 *
 * @param  array $variables
 * @return void
 */
function flat_access_level_display_preprocess_islandora_solr_facet_wrapper(&$variables) {

    module_load_include('inc', 'flat_access_level_display', 'includes/AccessLevelFacet');

    if ($variables['pid'] === AccessLevelFacet::FACET_FIELD) {

        global $_islandora_solr_queryclass;

        drupal_add_css(drupal_get_path('module', 'flat_access_level_display') . '/css/app.css');

        $accessLevelFacet = new AccessLevelFacet($_islandora_solr_queryclass);
        $variables['content'] = $accessLevelFacet->render();
    }
}
